CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255),
    role VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS leave_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    year_value INTEGER NOT NULL,
    total_days INTEGER NOT NULL,
    used_days INTEGER NOT NULL,
    remaining_days INTEGER NOT NULL,
    version INTEGER,
    CONSTRAINT fk_leave_balance_user FOREIGN KEY (user_id) REFERENCES users(id)
);
